version: "3.1"
services:
  
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db_data:/data
    environment:
      MYSQL_DATABASE: tu_apoyo
    restart: always
    networks:
      - tuapoyo    

networks:
  tuapoyo:
    driver: bridge